export const FETCH_DOSE_DETAIL_REQUEST = 'FETCH_DOSE_DETAIL_REQUEST';
export const FETCH_DOSE_DETAIL_SUCCESS = 'FETCH_DOSE_DETAIL_SUCCESS';
export const FETCH_DOSE_DETAIL_FAILURE = 'FETCH_DOSE_DETAIL_FAILURE';
export const UPDATE_DOSE_DETAIL_REQUEST = 'UPDATE_DOSE_DETAIL_REQUEST';
export const UPDATE_DOSE_DETAIL_SUCCESS = 'UPDATE_DOSE_DETAIL_SUCCESS';
export const UPDATE_DOSE_DETAIL_FAILURE = 'UPDATE_DOSE_DETAIL_FAILURE';
